### ISSUE TITLE
typo in usage

### ISSUE THREAD

**Issue by vedam** [TrySound/rollup-plugin-string#1]
small typo in usage

in usage you're passing an array to string():
```
plugins: [
  string([
    extensions: ['.html']
  ])
]
```

in your tests it's an object:
```
plugins: [
  string({
    extensions: ['.html', '.css']
  })
]
```

**Comment by TrySound** [comment]
@vedam Nice catch. Can you send a pr?

**Comment by TrySound** [comment]
Fix via https://github.com/TrySound/rollup-plugin-string/commit/154e7b155793ee5ba150f477a4b70daa1d378b6a
