### ISSUE TITLE
Strange export

### ISSUE THREAD

**Issue by SnarkBoojum** [TrySound/rollup-plugin-string#15]
The new version wasn't exporting the function like other rollup-plugin-* modules, so rollup couldn't use this plugin as-is ; I applied the following patch:
[unbreak.txt](https://github.com/TrySound/rollup-plugin-string/files/3402079/unbreak.txt)

**Comment by TrySound** [comment]
This plugin provides only commonjs output. On your side you should import like this
```js
import { string } from 'rollup-plugin-string'
```
