### ISSUE TITLE
Probably bad "main" field

### ISSUE THREAD

**Issue by guimard** [TrySound/rollup-plugin-string#16]
Hi,

package.json "main" field points to `index.js`. This fails with node 10.15.2. I replaced this value by `dist/rollup-plugin-string.js` then it succeed. Am I wrong ?

**Comment by guimard** [comment]
Then of course "files" field must be adjusted

**Comment by TrySound** [comment]
Which version of this plugin do you use?

**Comment by guimard** [comment]
3.0.0

**Comment by TrySound** [comment]
Show me your rollup config

**Comment by guimard** [comment]
```
import buble from 'rollup-plugin-buble';
  
var pkg = require('./package.json');

export default {
        entry: 'index.js',
        plugins: [buble()],
        targets: [
                {
                        format: 'cjs',
                        dest: pkg['main']
                },
                {
                        format: 'es6',
                        dest: pkg['jsnext:main']
                }
        ]
};
```
I packaged it for [Debian](https://www.debian.org)

**Comment by TrySound** [comment]
Are you sure you wanted to post this issue in rollup-plugin-string repo?

**Comment by guimard** [comment]
Your "mocha" test succeeds with my patch and fails without

**Comment by guimard** [comment]
I tried to compile rollup-plugin-string for Debian and to enable your test, where else do you want to post this issue ?

**Comment by TrySound** [comment]
I removed build step from this project long time ago. There is only index.js and main field points to it. There is no `dist` and not rollup.config.js anymore.

So I don't follow what is your issue.

**Comment by guimard** [comment]
Oups sorry, another developer made something wrong on Debian repo. Sorry for the noise
