### ISSUE TITLE
css files

### ISSUE THREAD

**Issue by dvnrsn** [TrySound/rollup-plugin-string#21]
Doesn't seem to work with css files...

```js
string({
      include: '**/*.css',
    })
```
```js
import styles from './some.css'
```
Error: 'default' is not exported...

Is this expected behavior? Should CSS files be supported?

**Comment by TrySound** [comment]
Yes, it should work. Try this include instead `/\.css$/`

**Comment by dvnrsn** [comment]
no longer needed this..
