### ISSUE TITLE
Typescript incompatible

### ISSUE THREAD

**Issue by AnthonyCrowcroft** [TrySound/rollup-plugin-string#22]
I can't for the life of me get this to work with our typescript library. It is based on this:
https://github.com/Hotell/typescript-lib-starter

any suggestions or direction would be super appreciated.

**Comment by jacksteamdev** [comment]
A [wildcard module declaration](https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations) should do the trick.

```typescript
// modules.d.ts
declare module '*.md' {
  const markdown: string
  export = markdown
}
```

**Comment by AnthonyCrowcroft** [comment]
awesome thanks heaps
