### ISSUE TITLE
Add option to encode content

### ISSUE THREAD

**Issue by Swatinem** [TrySound/rollup-plugin-string#3]
It would be nice if there was an option to, for example, base64 encode the file contents, or even make a data: URI out of them. Similar to what webpacks url-loader is doing.

If that is out of scope for this plugin, I will just create a separate plugin for my usecase. :-)

**Comment by TrySound** [comment]
I don't use webpack and don't know how it works. But uri request seems weird. This plugin just inlines text data in js. Where do you want to put uri?

About encoding. It's very specific case which will process every loaded file with this encoding. But I can add this. Or you can even make a PR. Just define load method.

**Comment by TrySound** [comment]
@Swatinem  Btw which usecase?

**Comment by Swatinem** [comment]
My usecase is something like this:

```js
import icon from '../assets/icon.svg';

// jsx
<div style={{backgroundImage: `url(${icon})`}>
```

I can do that in webpack using the `url-loader`. Thing is that I want to use both webpack & rollup, one for development with hot loading and one for minimal production bundles :-)

I will see what I can come up with over the weekend, expect a PR :-)

**Comment by TrySound** [comment]
This plugin is more for templates. But in your use case I'd like to recommend you to use external styles with https://github.com/TrySound/postcss-inline-svg. It's more clean way to process styles.

**Comment by TrySound** [comment]
Or at least this
https://github.com/postcss/postcss-js

**Comment by Swatinem** [comment]
That was just an example, for my usecase the style will end up in a `<style>` tag, just that I define everything in js, complete with prefixing etc, all I need now is to inline files as data-uris.
