### ISSUE TITLE
Use ES6 template strings instead of JSON.stringify()

### ISSUE THREAD

**Issue by Mevrael** [TrySound/rollup-plugin-string#4]
I can't use variables inside imported html templates because right now you are using JSON.stringify() on the content.

template.html:
```html
<div>
  ${name}
</div>
```

js:
```js
var name = 'John';

import tpl from './template.html';

console.log(tpl);
```

Does not works, it prints to console ${name} not John. If I replace
```js
code: 'export default ' + JSON.stringify(code) + ';',
```
to
```js
code: 'export default `' + code + '`;',
```

everything works.

**Comment by TrySound** [comment]
@Mevrael I think the idea of using local-global which will be executed in child module is incorrect and conflicts with the idea of modules. Template literal is not template angine. It should work only in current scope. Any module has different scope.

**Comment by Mevrael** [comment]
Indeed. What do you think about exporting functions with data parameter? So transpiled and bunlded code would look like
```js
var template = function(data) {
   return '<div>' + data.name + '</div>';
}
```

**Comment by Mevrael** [comment]
May be add an option for this.

Probably there could be also an option to pass a callback to format `code` before returning it.

**Comment by TrySound** [comment]
@Mevrael The idea of this plugin is loading only strings which can be passed in template engines. For example angular requires only template string and processes it inside. You can create own template plugin (but choose please sensible name).

**Comment by TrySound** [comment]
Plugins should be atomic and do only one thing.

**Comment by Mevrael** [comment]
Adding some new options would not break this idea.

Instead of
```js
str({
  extensions: ['.html']
}),
```
there could be:
```js

parser(content) {
   content = content.replace(),
   ...
   // format template for any framework or template engine without doing it in browser
}
   

str({
  extensions: ['.html', '.php'],
  format: 'template-closure',
  parser: parser
}),

**Comment by TrySound** [comment]
@Mevrael The name of this plugins is `string`, not `template`. I can add only some transform option for example to minify html.

**Comment by Mevrael** [comment]
Exactly, it's name is `string` and string > template since template is a subclass of string. String is a general data type.

And you just said about minification yourself, this breaks your minimalistic atomic phylosophy.

**Comment by TrySound** [comment]
@Mevrael It's about minification special type not js. Okay how do you wanna pass data to string? It should return function in this case. This plugin exports only strings.

**Comment by Mevrael** [comment]
as I said if I wanna use another format I pass it to options
```js
import tpl from './template.html';

let user = ...

let data = {
   user: user
};

console.log(tpl(data));
```

**Comment by TrySound** [comment]
Oh, you still about template syntax. I can't do this. Plugins should return es5 stuff. Templates is not about that.

**Comment by TrySound** [comment]
@Mevrael Use custom plugin for this case.

**Comment by Mevrael** [comment]
There is tool called Babel and plugin for rollup also...

Anyway thank you for conversation, I'll made my own plugin for general use cases.

**Comment by TrySound** [comment]
Babel should process only user script, not generated.
