### ISSUE TITLE
SourceMap error with 2.0.0

### ISSUE THREAD

**Issue by csvn** [TrySound/rollup-plugin-string#6]
I get the error "Cannot generate sourcemap if non-sourcemap-generating transformers are used". Downgrading to 1.0.1 (with the corresponding options change) removes the error.

I believe this change is the culprit:
[v1.0.1](https://github.com/TrySound/rollup-plugin-string/blob/v1.0.1/src/index.js#L14-L17) -> [v2.0.0](https://github.com/TrySound/rollup-plugin-string/blob/master/index.js#L13)

From [rollup plugin wiki](https://github.com/rollup/rollup/wiki/Plugins#conventions):
> If a plugin transforms source code, it should generate a sourcemap automatically, unless there's a specific sourceMap: false option. Rollup only cares about the mappings property (everything else is handled automatically). If it doesn't make sense to generate a sourcemap (e.g. rollup-plugin-string, return an empty sourcemap

**Comment by TrySound** [comment]
@csvn Hi. Thanks for reporting. Accidentally changed this. Can you send a PR?

**Comment by csvn** [comment]
@TrySound created a pull request. Verified it locally only (with `npm link`), but didn't write any tests for it.

**Comment by TrySound** [comment]
@csvn Released 2.0.1

**Comment by csvn** [comment]
Sweet! Feel free to close the issue
